-- ============================================================================
-- CARELINK UNIFIED POSTGRESQL / SUPABASE DATABASE SCHEMA
-- Auto-generated by concatenating migrations 01 through 14 in dependency order
-- ============================================================================


-- >>> START OF 20260907000001_extensions_and_enums.sql <<<
-- ============================================================================
-- Migration: 20260907000001_extensions_and_enums.sql
-- Description: Core PostgreSQL extensions and domain-specific ENUM definitions
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. CORE ROLES & PERMISSIONS
DO $$ BEGIN
    CREATE TYPE app_role AS ENUM (
        'patient',
        'doctor',
        'pharmacy_admin',
        'pharmacy_staff',
        'platform_admin'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 3. MEDICAL & BIOLOGICAL ENUMS
DO $$ BEGIN
    CREATE TYPE gender_type AS ENUM (
        'male',
        'female',
        'other',
        'unspecified'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE blood_group_type AS ENUM (
        'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'unknown'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE doctor_verification_status AS ENUM (
        'pending',
        'verified',
        'rejected',
        'suspended'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 4. ACCESS CONTROL ENUMS (MEDICAL RECORD)
DO $$ BEGIN
    CREATE TYPE access_level_type AS ENUM (
        'read_only',
        'read_write',
        'full'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE access_status_type AS ENUM (
        'active',
        'revoked',
        'expired'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 5. SLOTS, APPOINTMENTS & CONSULTATIONS
DO $$ BEGIN
    CREATE TYPE slot_status_type AS ENUM (
        'available',
        'booked',
        'blocked',
        'cancelled'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE consultation_mode_type AS ENUM (
        'in_person',
        'teleconsultation',
        'home_visit'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE appointment_status_type AS ENUM (
        'requested',
        'confirmed',
        'in_progress',
        'completed',
        'cancelled',
        'no_show',
        'transferred'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE consultation_status_type AS ENUM (
        'draft',
        'in_progress',
        'completed',
        'cancelled'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 6. PRESCRIPTIONS & PHARMACY TRANSFERS
DO $$ BEGIN
    CREATE TYPE prescription_status_type AS ENUM (
        'active',
        'partially_dispensed',
        'dispensed',
        'expired',
        'cancelled'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE transfer_status_type AS ENUM (
        'pending',
        'accepted',
        'rejected',
        'dispensing',
        'completed',
        'cancelled'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 7. STOCK & INVENTORY
DO $$ BEGIN
    CREATE TYPE stock_movement_type AS ENUM (
        'entry',
        'sale',
        'adjustment',
        'reservation',
        'release_reservation',
        'return',
        'loss',
        'expiry'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 8. ORDERS & FULFILLMENT (MARKETPLACE)
DO $$ BEGIN
    CREATE TYPE order_status_type AS ENUM (
        'pending',
        'confirmed',
        'processing',
        'partially_fulfilled',
        'ready_for_pickup',
        'out_for_delivery',
        'delivered',
        'completed',
        'cancelled'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE fulfillment_status_type AS ENUM (
        'pending',
        'accepted',
        'preparing',
        'ready_for_pickup',
        'completed',
        'rejected',
        'cancelled'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE delivery_mode_type AS ENUM (
        'pickup',
        'standard_delivery',
        'express_delivery'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 9. PAYMENTS & INSURANCE CLAIMS
DO $$ BEGIN
    CREATE TYPE payment_method_type AS ENUM (
        'tmoney',
        'yas',
        'moov_money',
        'gozem',
        'card',
        'paypal',
        'cash_on_delivery',
        'cash_in_person'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE payment_status_type AS ENUM (
        'pending',
        'processing',
        'succeeded',
        'failed',
        'cancelled',
        'refunded'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE claim_status_type AS ENUM (
        'draft',
        'submitted',
        'under_review',
        'approved',
        'rejected',
        'paid'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 10. NOTIFICATIONS
DO $$ BEGIN
    CREATE TYPE notification_type AS ENUM (
        'appointment',
        'prescription',
        'order',
        'stock',
        'access_request',
        'system'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- >>> END OF 20260907000001_extensions_and_enums.sql <<<


-- >>> START OF 20260907000002_core_profiles_and_roles.sql <<<
-- ============================================================================
-- Migration: 20260907000002_core_profiles_and_roles.sql
-- Description: Profiles, role safeguards, patient/doctor/pharmacy entities
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. BASE USER PROFILES TABLE (Linked to auth.users)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role app_role NOT NULL DEFAULT 'patient',
    email TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT,
    avatar_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index on email & role for quick lookup
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_email ON profiles(email);

-- 2. TRIGGER: Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_profiles_updated_at
BEFORE UPDATE ON profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 3. TRIGGER: Prevent unauthorized role escalation
-- Only platform_admin or service_role can elevate a user's role
CREATE OR REPLACE FUNCTION prevent_unauthorized_role_escalation()
RETURNS TRIGGER AS $$
DECLARE
    v_caller_role app_role;
BEGIN
    -- If role is not changing, allow update
    IF OLD.role = NEW.role THEN
        RETURN NEW;
    END IF;

    -- If executing via service_role or background superuser
    IF auth.role() = 'service_role' THEN
        RETURN NEW;
    END IF;

    -- Check if current authenticated user has platform_admin role
    SELECT role INTO v_caller_role FROM profiles WHERE id = auth.uid();
    IF v_caller_role IS DISTINCT FROM 'platform_admin' THEN
        RAISE EXCEPTION 'Action interdite : vous ne pouvez pas modifier votre propre rôle ou attribuer des privilèges supérieurs.'
            USING ERRCODE = '42501';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_prevent_role_escalation
BEFORE UPDATE OF role ON profiles
FOR EACH ROW EXECUTE FUNCTION prevent_unauthorized_role_escalation();

-- 4. PATIENT PROFILES
CREATE TABLE IF NOT EXISTS patient_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
    date_of_birth DATE,
    gender gender_type NOT NULL DEFAULT 'unspecified',
    blood_group blood_group_type NOT NULL DEFAULT 'unknown',
    allergies TEXT[] NOT NULL DEFAULT '{}',
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    address TEXT,
    city TEXT,
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_patient_profiles_user ON patient_profiles(profile_id);

CREATE TRIGGER trg_patient_profiles_updated_at
BEFORE UPDATE ON patient_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 5. DOCTOR PROFILES
CREATE TABLE IF NOT EXISTS doctor_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
    license_number TEXT NOT NULL UNIQUE,
    specialty TEXT NOT NULL,
    sub_specialties TEXT[] NOT NULL DEFAULT '{}',
    bio TEXT,
    consultation_fee NUMERIC(12, 2) NOT NULL DEFAULT 10000.00, -- FCFA
    currency TEXT NOT NULL DEFAULT 'XOF',
    verification_status doctor_verification_status NOT NULL DEFAULT 'pending',
    verified_at TIMESTAMPTZ,
    verified_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    signature_url TEXT,
    stamp_url TEXT,
    office_address TEXT,
    office_city TEXT,
    office_latitude NUMERIC(10, 7),
    office_longitude NUMERIC(10, 7),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_doctor_profiles_specialty ON doctor_profiles(specialty);
CREATE INDEX IF NOT EXISTS idx_doctor_profiles_status ON doctor_profiles(verification_status);

CREATE TRIGGER trg_doctor_profiles_updated_at
BEFORE UPDATE ON doctor_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 6. PHARMACIES
CREATE TABLE IF NOT EXISTS pharmacies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    license_number TEXT NOT NULL UNIQUE,
    address TEXT NOT NULL,
    district TEXT, -- Quartier
    city TEXT NOT NULL,
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    opening_hours JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_duty_pharmacy BOOLEAN NOT NULL DEFAULT false, -- Pharmacie de garde
    is_verified BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pharmacies_city ON pharmacies(city);
CREATE INDEX IF NOT EXISTS idx_pharmacies_coords ON pharmacies(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_pharmacies_verified ON pharmacies(is_verified, is_active);

CREATE TRIGGER trg_pharmacies_updated_at
BEFORE UPDATE ON pharmacies
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 7. PHARMACY STAFF (Affiliation of pharmacists/staff to a pharmacy)
CREATE TABLE IF NOT EXISTS pharmacy_staff (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pharmacy_id UUID NOT NULL REFERENCES pharmacies(id) ON DELETE CASCADE,
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    staff_role TEXT NOT NULL DEFAULT 'pharmacist', -- 'admin', 'pharmacist', 'assistant'
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_pharmacy_staff_profile UNIQUE (pharmacy_id, profile_id)
);

CREATE INDEX IF NOT EXISTS idx_pharmacy_staff_user ON pharmacy_staff(profile_id);
CREATE INDEX IF NOT EXISTS idx_pharmacy_staff_pharmacy ON pharmacy_staff(pharmacy_id);

CREATE TRIGGER trg_pharmacy_staff_updated_at
BEFORE UPDATE ON pharmacy_staff
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 8. TRIGGER: Auto-create Profile & Patient Profile on auth.users Signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    v_role app_role := 'patient';
    v_first_name TEXT := '';
    v_last_name TEXT := '';
    v_meta_role TEXT;
BEGIN
    -- Extract optional role from raw_user_meta_data if passed during signup
    v_meta_role := NEW.raw_user_meta_data->>'role';
    IF v_meta_role IN ('patient', 'doctor', 'pharmacy_admin') THEN
        v_role := v_meta_role::app_role;
    END IF;

    v_first_name := COALESCE(NEW.raw_user_meta_data->>'first_name', 'Utilisateur');
    v_last_name := COALESCE(NEW.raw_user_meta_data->>'last_name', 'CareLink');

    INSERT INTO public.profiles (id, email, role, first_name, last_name, phone)
    VALUES (
        NEW.id,
        NEW.email,
        v_role,
        v_first_name,
        v_last_name,
        NEW.raw_user_meta_data->>'phone'
    );

    -- If registered as a patient, auto-create patient_profile
    IF v_role = 'patient' THEN
        INSERT INTO public.patient_profiles (profile_id)
        VALUES (NEW.id);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Connect trigger to auth.users if available
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'auth' AND table_name = 'users'
    ) THEN
        DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
        CREATE TRIGGER on_auth_user_created
        AFTER INSERT ON auth.users
        FOR EACH ROW EXECUTE FUNCTION handle_new_user();
    END IF;
END $$;

-- >>> END OF 20260907000002_core_profiles_and_roles.sql <<<


-- >>> START OF 20260907000003_medical_records.sql <<<
-- ============================================================================
-- Migration: 20260907000003_medical_records.sql
-- Description: Medical dossiers, timeline entries, access delegation & transfers
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. MEDICAL DOSSIER (Root health record for a patient)
CREATE TABLE IF NOT EXISTS medical_dossiers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID NOT NULL UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
    blood_group blood_group_type NOT NULL DEFAULT 'unknown',
    allergies TEXT[] NOT NULL DEFAULT '{}',
    chronic_conditions TEXT[] NOT NULL DEFAULT '{}',
    past_medical_history TEXT,
    surgical_history TEXT,
    family_history TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_medical_dossiers_patient ON medical_dossiers(patient_id);

CREATE TRIGGER trg_medical_dossiers_updated_at
BEFORE UPDATE ON medical_dossiers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 2. MEDICAL RECORD ENTRIES (Observations, diagnoses, exams, consultation notes)
CREATE TABLE IF NOT EXISTS medical_record_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dossier_id UUID NOT NULL REFERENCES medical_dossiers(id) ON DELETE CASCADE,
    doctor_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    entry_type TEXT NOT NULL, -- 'consultation_note', 'diagnosis', 'observation', 'treatment_plan', 'lab_result', 'document'
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    attachments JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of storage document paths / metadata
    is_sensitive BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_record_entries_dossier ON medical_record_entries(dossier_id);
CREATE INDEX IF NOT EXISTS idx_record_entries_doctor ON medical_record_entries(doctor_id);
CREATE INDEX IF NOT EXISTS idx_record_entries_type ON medical_record_entries(entry_type);

CREATE TRIGGER trg_medical_record_entries_updated_at
BEFORE UPDATE ON medical_record_entries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 3. DOCTOR-PATIENT ACCESS CONTROL (Strict access delegation)
CREATE TABLE IF NOT EXISTS doctor_patient_access (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    doctor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    granted_by UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    reason TEXT,
    access_level access_level_type NOT NULL DEFAULT 'read_write',
    status access_status_type NOT NULL DEFAULT 'active',
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revocation_reason TEXT,
    CONSTRAINT uq_doctor_patient_access UNIQUE(doctor_id, patient_id)
);

CREATE INDEX IF NOT EXISTS idx_dp_access_doctor ON doctor_patient_access(doctor_id);
CREATE INDEX IF NOT EXISTS idx_dp_access_patient ON doctor_patient_access(patient_id);
CREATE INDEX IF NOT EXISTS idx_dp_access_active ON doctor_patient_access(doctor_id, patient_id, status);

-- 4. DOSSIER TRANSFERS (Transfer of a patient record between Doctor A and Doctor B)
CREATE TABLE IF NOT EXISTS dossier_transfers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dossier_id UUID NOT NULL REFERENCES medical_dossiers(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    from_doctor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    to_doctor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    transfer_reason TEXT NOT NULL,
    clinical_summary TEXT,
    status transfer_status_type NOT NULL DEFAULT 'pending',
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    responded_at TIMESTAMPTZ,
    response_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dossier_transfers_from ON dossier_transfers(from_doctor_id);
CREATE INDEX IF NOT EXISTS idx_dossier_transfers_to ON dossier_transfers(to_doctor_id);
CREATE INDEX IF NOT EXISTS idx_dossier_transfers_patient ON dossier_transfers(patient_id);

CREATE TRIGGER trg_dossier_transfers_updated_at
BEFORE UPDATE ON dossier_transfers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Auto-create medical_dossier when patient_profile is created
CREATE OR REPLACE FUNCTION auto_create_medical_dossier()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.medical_dossiers (patient_id, blood_group, allergies)
    VALUES (NEW.profile_id, NEW.blood_group, NEW.allergies)
    ON CONFLICT (patient_id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_auto_create_medical_dossier
AFTER INSERT ON patient_profiles
FOR EACH ROW EXECUTE FUNCTION auto_create_medical_dossier();

-- >>> END OF 20260907000003_medical_records.sql <<<


-- >>> START OF 20260907000004_slots_and_appointments.sql <<<
-- ============================================================================
-- Migration: 20260907000004_slots_and_appointments.sql
-- Description: Real doctor availability slots, appointment bookings & consultations
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. DOCTOR AVAILABILITY SLOTS
CREATE TABLE IF NOT EXISTS doctor_slots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    doctor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status slot_status_type NOT NULL DEFAULT 'available',
    consultation_mode consultation_mode_type NOT NULL DEFAULT 'in_person',
    capacity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_slot_time CHECK (end_time > start_time),
    CONSTRAINT chk_slot_capacity CHECK (capacity >= 1)
);

CREATE INDEX IF NOT EXISTS idx_slots_doctor_time ON doctor_slots(doctor_id, start_time);
CREATE INDEX IF NOT EXISTS idx_slots_status ON doctor_slots(doctor_id, status);

CREATE TRIGGER trg_doctor_slots_updated_at
BEFORE UPDATE ON doctor_slots
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 2. APPOINTMENTS
CREATE TABLE IF NOT EXISTS appointments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    doctor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    slot_id UUID REFERENCES doctor_slots(id) ON DELETE SET NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    duration_minutes INTEGER NOT NULL DEFAULT 30,
    status appointment_status_type NOT NULL DEFAULT 'requested',
    consultation_mode consultation_mode_type NOT NULL DEFAULT 'in_person',
    reason_for_visit TEXT NOT NULL,
    patient_notes TEXT,
    cancellation_reason TEXT,
    cancelled_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_appointments_patient ON appointments(patient_id, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_appointments_doctor ON appointments(doctor_id, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_appointments_slot ON appointments(slot_id);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON appointments(status);

CREATE TRIGGER trg_appointments_updated_at
BEFORE UPDATE ON appointments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 3. MEDICAL CONSULTATIONS
CREATE TABLE IF NOT EXISTS consultations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    appointment_id UUID UNIQUE REFERENCES appointments(id) ON DELETE SET NULL,
    doctor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    status consultation_status_type NOT NULL DEFAULT 'in_progress',
    symptoms TEXT,
    vital_signs JSONB NOT NULL DEFAULT '{}'::jsonb, -- blood_pressure, temperature, heart_rate, weight_kg, height_cm, bmi
    physical_examination TEXT,
    diagnosis TEXT,
    clinical_notes TEXT,
    treatment_plan TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_consultations_doctor ON consultations(doctor_id, started_at);
CREATE INDEX IF NOT EXISTS idx_consultations_patient ON consultations(patient_id, started_at);
CREATE INDEX IF NOT EXISTS idx_consultations_appointment ON consultations(appointment_id);

CREATE TRIGGER trg_consultations_updated_at
BEFORE UPDATE ON consultations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Automatically grant doctor-patient access when an appointment is confirmed
CREATE OR REPLACE FUNCTION handle_appointment_access_grant()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'confirmed' AND (OLD.status IS DISTINCT FROM 'confirmed') THEN
        INSERT INTO public.doctor_patient_access (
            doctor_id,
            patient_id,
            granted_by,
            reason,
            access_level,
            status,
            expires_at
        )
        VALUES (
            NEW.doctor_id,
            NEW.patient_id,
            NEW.patient_id,
            'Rendez-vous médical confirmé',
            'read_write',
            'active',
            NEW.scheduled_at + INTERVAL '30 days' -- Accès valide jusqu'à 30 jours après le rendez-vous
        )
        ON CONFLICT (doctor_id, patient_id) DO UPDATE
        SET status = 'active',
            expires_at = GREATEST(doctor_patient_access.expires_at, NEW.scheduled_at + INTERVAL '30 days'),
            revoked_at = NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_appointment_confirmed_grant_access
AFTER UPDATE OF status ON appointments
FOR EACH ROW EXECUTE FUNCTION handle_appointment_access_grant();

-- >>> END OF 20260907000004_slots_and_appointments.sql <<<


-- >>> START OF 20260907000005_prescriptions.sql <<<
-- ============================================================================
-- Migration: 20260907000005_prescriptions.sql
-- Description: Digital prescriptions, line items & patient-initiated pharmacy transfers
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. DIGITAL PRESCRIPTIONS (Ordonnances électroniques)
CREATE TABLE IF NOT EXISTS prescriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    consultation_id UUID REFERENCES consultations(id) ON DELETE SET NULL,
    doctor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    prescription_code TEXT NOT NULL UNIQUE, -- E.g. 'RX-202609-AB12CD'
    status prescription_status_type NOT NULL DEFAULT 'active',
    general_instructions TEXT,
    doctor_signature_url TEXT,
    doctor_stamp_url TEXT,
    is_digitally_signed BOOLEAN NOT NULL DEFAULT false,
    signed_at TIMESTAMPTZ,
    valid_until TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '3 months'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_prescriptions_patient ON prescriptions(patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_prescriptions_doctor ON prescriptions(doctor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_prescriptions_code ON prescriptions(prescription_code);
CREATE INDEX IF NOT EXISTS idx_prescriptions_status ON prescriptions(status);

CREATE TRIGGER trg_prescriptions_updated_at
BEFORE UPDATE ON prescriptions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 2. PRESCRIPTION ITEMS (Médicaments prescrits)
CREATE TABLE IF NOT EXISTS prescription_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    prescription_id UUID NOT NULL REFERENCES prescriptions(id) ON DELETE CASCADE,
    medication_name TEXT NOT NULL,
    brand TEXT,
    form TEXT NOT NULL, -- comprimé, gélule, sirop, injectable, pommade, collyre
    dosage TEXT NOT NULL, -- 500 mg, 1 g, 100 mg/ml
    quantity INTEGER NOT NULL DEFAULT 1,
    frequency TEXT NOT NULL, -- ex: "1 comprimé matin et soir après le repas"
    duration_days INTEGER NOT NULL DEFAULT 7,
    instructions TEXT,
    is_renewable BOOLEAN NOT NULL DEFAULT false,
    renewals_allowed INTEGER NOT NULL DEFAULT 0,
    renewals_remaining INTEGER NOT NULL DEFAULT 0,
    is_dispensed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_prescription_items_rx ON prescription_items(prescription_id);

-- 3. PATIENT-INITIATED PHARMACY TRANSFERS (Transfert volontaire vers une officine choisie)
CREATE TABLE IF NOT EXISTS prescription_pharmacy_transfers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    prescription_id UUID NOT NULL REFERENCES prescriptions(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    pharmacy_id UUID NOT NULL REFERENCES pharmacies(id) ON DELETE CASCADE,
    status transfer_status_type NOT NULL DEFAULT 'pending',
    patient_notes TEXT,
    pharmacy_response_notes TEXT,
    transferred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    responded_at TIMESTAMPTZ,
    responded_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rx_transfers_rx ON prescription_pharmacy_transfers(prescription_id);
CREATE INDEX IF NOT EXISTS idx_rx_transfers_pharmacy ON prescription_pharmacy_transfers(pharmacy_id, status);
CREATE INDEX IF NOT EXISTS idx_rx_transfers_patient ON prescription_pharmacy_transfers(patient_id);

CREATE TRIGGER trg_rx_transfers_updated_at
BEFORE UPDATE ON prescription_pharmacy_transfers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Auto-generate readable unique prescription code
CREATE OR REPLACE FUNCTION generate_prescription_code()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.prescription_code IS NULL OR NEW.prescription_code = '' THEN
        NEW.prescription_code := 'RX-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substring(encode(gen_random_bytes(4), 'hex') from 1 for 6));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_prescription_code
BEFORE INSERT ON prescriptions
FOR EACH ROW EXECUTE FUNCTION generate_prescription_code();

-- >>> END OF 20260907000005_prescriptions.sql <<<


-- >>> START OF 20260907000006_pharmacy_and_inventory.sql <<<
-- ============================================================================
-- Migration: 20260907000006_pharmacy_and_inventory.sql
-- Description: Product catalog, categories, real-time stock & audited stock movements
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. PRODUCT CATEGORIES (Taxonomie pharmaceutique)
CREATE TABLE IF NOT EXISTS product_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    parent_id UUID REFERENCES product_categories(id) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_categories_slug ON product_categories(slug);
CREATE INDEX IF NOT EXISTS idx_categories_parent ON product_categories(parent_id);

-- 2. PRODUCTS (Articles vendus par chaque officine)
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pharmacy_id UUID NOT NULL REFERENCES pharmacies(id) ON DELETE CASCADE,
    category_id UUID REFERENCES product_categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    brand TEXT,
    generic_name TEXT, -- DCI (Dénomination Commune Internationale)
    form TEXT NOT NULL, -- Comprimé, Sirop, Gélule, Pommade, Solution injectable
    dosage TEXT NOT NULL, -- 500 mg, 1 g, 10 mg/ml
    description TEXT,
    price NUMERIC(12, 2) NOT NULL, -- En FCFA
    currency TEXT NOT NULL DEFAULT 'XOF',
    is_prescription_required BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    sku TEXT,
    barcode TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_product_price CHECK (price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_products_pharmacy ON products(pharmacy_id);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_name ON products(name);
CREATE INDEX IF NOT EXISTS idx_products_generic ON products(generic_name);
CREATE INDEX IF NOT EXISTS idx_products_active ON products(is_active);

CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 3. PRODUCT STOCKS (Niveau actuel de stock)
CREATE TABLE IF NOT EXISTS product_stocks (
    product_id UUID PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
    pharmacy_id UUID NOT NULL REFERENCES pharmacies(id) ON DELETE CASCADE,
    current_quantity INTEGER NOT NULL DEFAULT 0,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,
    low_stock_threshold INTEGER NOT NULL DEFAULT 5,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_stock_non_negative CHECK (current_quantity >= 0),
    CONSTRAINT chk_reserved_non_negative CHECK (reserved_quantity >= 0),
    CONSTRAINT chk_reserved_lte_current CHECK (reserved_quantity <= current_quantity)
);

CREATE INDEX IF NOT EXISTS idx_stocks_pharmacy ON product_stocks(pharmacy_id);
CREATE INDEX IF NOT EXISTS idx_stocks_quantity ON product_stocks(current_quantity);

CREATE TRIGGER trg_product_stocks_updated_at
BEFORE UPDATE ON product_stocks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Auto-initialize product_stocks row on product creation
CREATE OR REPLACE FUNCTION handle_product_created()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.product_stocks (product_id, pharmacy_id, current_quantity, reserved_quantity)
    VALUES (NEW.id, NEW.pharmacy_id, 0, 0)
    ON CONFLICT (product_id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_on_product_created
AFTER INSERT ON products
FOR EACH ROW EXECUTE FUNCTION handle_product_created();

-- 4. STOCK MOVEMENTS (Grand livre immuable des flux de stock)
CREATE TABLE IF NOT EXISTS stock_movements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    pharmacy_id UUID NOT NULL REFERENCES pharmacies(id) ON DELETE CASCADE,
    movement_type stock_movement_type NOT NULL,
    quantity_change INTEGER NOT NULL, -- Ex: +50 (réception), -2 (vente), -1 (perte)
    quantity_before INTEGER NOT NULL,
    quantity_after INTEGER NOT NULL,
    reference_type TEXT NOT NULL, -- 'order', 'manual_adjustment', 'initial_stock', 'inventory_audit', 'prescription_dispense'
    reference_id TEXT,
    notes TEXT,
    performed_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_stock_movements_product ON stock_movements(product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_movements_pharmacy ON stock_movements(pharmacy_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_movements_type ON stock_movements(movement_type);

-- >>> END OF 20260907000006_pharmacy_and_inventory.sql <<<


-- >>> START OF 20260907000007_marketplace_orders.sql <<<
-- ============================================================================
-- Migration: 20260907000007_marketplace_orders.sql
-- Description: Multi-pharmacy shopping carts, parent orders & partitioned fulfillments
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. SHOPPING CARTS (Panier du patient)
CREATE TABLE IF NOT EXISTS carts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID NOT NULL UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_carts_updated_at
BEFORE UPDATE ON carts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 2. CART ITEMS (Lignes du panier)
CREATE TABLE IF NOT EXISTS cart_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cart_id UUID NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    pharmacy_id UUID NOT NULL REFERENCES pharmacies(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_cart_quantity CHECK (quantity > 0),
    CONSTRAINT uq_cart_product UNIQUE (cart_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_cart_items_cart ON cart_items(cart_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_pharmacy ON cart_items(pharmacy_id);

CREATE TRIGGER trg_cart_items_updated_at
BEFORE UPDATE ON cart_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 3. ORDERS (Commande mère globale du patient)
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    order_number TEXT NOT NULL UNIQUE,
    status order_status_type NOT NULL DEFAULT 'pending',
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    insurance_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    patient_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    currency TEXT NOT NULL DEFAULT 'XOF',
    payment_status payment_status_type NOT NULL DEFAULT 'pending',
    delivery_mode delivery_mode_type NOT NULL DEFAULT 'pickup',
    delivery_address TEXT,
    delivery_city TEXT,
    delivery_latitude NUMERIC(10, 7),
    delivery_longitude NUMERIC(10, 7),
    patient_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_orders_patient ON orders(patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_number ON orders(order_number);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

CREATE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 4. ORDER FULFILLMENTS (Sous-commandes spécifiques à chaque pharmacie)
CREATE TABLE IF NOT EXISTS order_fulfillments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    pharmacy_id UUID NOT NULL REFERENCES pharmacies(id) ON DELETE CASCADE,
    fulfillment_number TEXT NOT NULL UNIQUE,
    subtotal_amount NUMERIC(12, 2) NOT NULL,
    status fulfillment_status_type NOT NULL DEFAULT 'pending',
    rejection_reason TEXT,
    prepared_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fulfillments_order ON order_fulfillments(order_id);
CREATE INDEX IF NOT EXISTS idx_fulfillments_pharmacy ON order_fulfillments(pharmacy_id, status);

CREATE TRIGGER trg_order_fulfillments_updated_at
BEFORE UPDATE ON order_fulfillments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 5. ORDER ITEMS (Articles détaillés attachés au fulfillment)
CREATE TABLE IF NOT EXISTS order_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_fulfillment_id UUID NOT NULL REFERENCES order_fulfillments(id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(12, 2) NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_order_item_quantity CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_order_items_fulfillment ON order_items(order_fulfillment_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items(product_id);

-- Auto-generate readable unique order number
CREATE OR REPLACE FUNCTION generate_order_number()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.order_number IS NULL OR NEW.order_number = '' THEN
        NEW.order_number := 'ORD-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substring(encode(gen_random_bytes(4), 'hex') from 1 for 6));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_generate_order_number
BEFORE INSERT ON orders
FOR EACH ROW EXECUTE FUNCTION generate_order_number();

-- >>> END OF 20260907000007_marketplace_orders.sql <<<


-- >>> START OF 20260907000008_insurance_and_claims.sql <<<
-- ============================================================================
-- Migration: 20260907000008_insurance_and_claims.sql
-- Description: Health insurance providers, patient policies, coverages & tiers-payant claims
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. INSURANCE PROVIDERS (Compagnies d'assurance)
CREATE TABLE IF NOT EXISTS insurance_providers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE, -- E.g. 'SUNU', 'ASCOMA', 'NSIA', 'SANLAM', 'OGAR'
    contact_phone TEXT,
    contact_email TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. PATIENT INSURANCES (Police et carte d'assuré du patient)
CREATE TABLE IF NOT EXISTS patient_insurances (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id UUID NOT NULL REFERENCES insurance_providers(id) ON DELETE RESTRICT,
    policy_number TEXT NOT NULL,
    member_id TEXT NOT NULL,
    coverage_rate_default NUMERIC(5, 2) NOT NULL DEFAULT 80.00, -- En %
    is_verified BOOLEAN NOT NULL DEFAULT false,
    valid_from DATE NOT NULL,
    valid_until DATE NOT NULL,
    card_document_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_coverage_rate CHECK (coverage_rate_default >= 0 AND coverage_rate_default <= 100),
    CONSTRAINT chk_valid_period CHECK (valid_until >= valid_from)
);

CREATE INDEX IF NOT EXISTS idx_patient_insurances_patient ON patient_insurances(patient_id);
CREATE INDEX IF NOT EXISTS idx_patient_insurances_provider ON patient_insurances(provider_id);

CREATE TRIGGER trg_patient_insurances_updated_at
BEFORE UPDATE ON patient_insurances
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 3. INSURANCE COVERAGES (Règles spécifiques par catégorie médicale / pharmaceutique)
CREATE TABLE IF NOT EXISTS insurance_coverages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider_id UUID NOT NULL REFERENCES insurance_providers(id) ON DELETE CASCADE,
    category_id UUID REFERENCES product_categories(id) ON DELETE CASCADE,
    coverage_percentage NUMERIC(5, 2) NOT NULL,
    ceiling_amount NUMERIC(12, 2), -- Plafond max en FCFA
    requires_preauth BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_coverages_provider ON insurance_coverages(provider_id);

-- 4. INSURANCE CLAIMS (Feuilles de soins et réclamations de tiers-payant)
CREATE TABLE IF NOT EXISTS insurance_claims (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    claim_reference TEXT NOT NULL UNIQUE,
    patient_insurance_id UUID NOT NULL REFERENCES patient_insurances(id) ON DELETE RESTRICT,
    order_id UUID REFERENCES orders(id) ON DELETE SET NULL,
    consultation_id UUID REFERENCES consultations(id) ON DELETE SET NULL,
    claimed_amount NUMERIC(12, 2) NOT NULL,
    approved_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    patient_copay_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    status claim_status_type NOT NULL DEFAULT 'submitted',
    rejection_reason TEXT,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ,
    processed_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_claims_insurance ON insurance_claims(patient_insurance_id);
CREATE INDEX IF NOT EXISTS idx_claims_order ON insurance_claims(order_id);
CREATE INDEX IF NOT EXISTS idx_claims_consultation ON insurance_claims(consultation_id);
CREATE INDEX IF NOT EXISTS idx_claims_status ON insurance_claims(status);

CREATE TRIGGER trg_insurance_claims_updated_at
BEFORE UPDATE ON insurance_claims
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Auto-generate claim reference
CREATE OR REPLACE FUNCTION generate_claim_reference()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.claim_reference IS NULL OR NEW.claim_reference = '' THEN
        NEW.claim_reference := 'CLM-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substring(encode(gen_random_bytes(4), 'hex') from 1 for 6));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_generate_claim_reference
BEFORE INSERT ON insurance_claims
FOR EACH ROW EXECUTE FUNCTION generate_claim_reference();

-- >>> END OF 20260907000008_insurance_and_claims.sql <<<


-- >>> START OF 20260907000009_payments_and_notifications.sql <<<
-- ============================================================================
-- Migration: 20260907000009_payments_and_notifications.sql
-- Description: Financial payment audit (no sensitive card storage) & real-time notification engine
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. PAYMENTS (Audit financier sans stockage de numéros de carte bancaire)
CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID REFERENCES orders(id) ON DELETE SET NULL,
    consultation_id UUID REFERENCES consultations(id) ON DELETE SET NULL,
    patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    amount NUMERIC(12, 2) NOT NULL,
    currency TEXT NOT NULL DEFAULT 'XOF',
    payment_method payment_method_type NOT NULL,
    status payment_status_type NOT NULL DEFAULT 'pending',
    provider_tx_id TEXT, -- ID de transaction de la passerelle (T-Money, Moov Money, Gozem, etc.)
    external_reference TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    initiated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_payment_amount CHECK (amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_payments_patient ON payments(patient_id);
CREATE INDEX IF NOT EXISTS idx_payments_order ON payments(order_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_reference ON payments(external_reference);

CREATE TRIGGER trg_payments_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 2. NOTIFICATIONS (Moteur de notifications push & in-app)
CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    recipient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    notification_type notification_type NOT NULL DEFAULT 'system',
    data JSONB NOT NULL DEFAULT '{}'::jsonb, -- Action deep-link, IDs d'objets, etc.
    is_read BOOLEAN NOT NULL DEFAULT false,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(recipient_id, is_read, created_at DESC);

-- Trigger: When order status changes, auto-notify patient
CREATE OR REPLACE FUNCTION notify_order_status_change()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status IS DISTINCT FROM OLD.status THEN
        INSERT INTO public.notifications (recipient_id, title, message, notification_type, data)
        VALUES (
            NEW.patient_id,
            'Statut de votre commande',
            'Votre commande ' || NEW.order_number || ' est maintenant : ' || NEW.status::TEXT,
            'order',
            jsonb_build_object('order_id', NEW.id, 'order_number', NEW.order_number, 'status', NEW.status)
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_order_notify_patient
AFTER UPDATE OF status ON orders
FOR EACH ROW EXECUTE FUNCTION notify_order_status_change();

-- >>> END OF 20260907000009_payments_and_notifications.sql <<<


-- >>> START OF 20260907000010_audit_logging.sql <<<
-- ============================================================================
-- Migration: 20260907000010_audit_logging.sql
-- Description: Healthcare legal audit trail (HIPAA/GDPR compliance equivalent)
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. AUDIT LOGS TABLE
CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    action TEXT NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE', 'ACCESS_VIEW', 'PRESCRIPTION_SIGN', 'STOCK_TRANSACTION'
    resource_type TEXT NOT NULL, -- 'medical_dossier', 'prescription', 'order', 'stock', 'role_change'
    resource_id TEXT NOT NULL,
    old_values JSONB,
    new_values JSONB,
    ip_address TEXT,
    user_agent TEXT,
    performed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON audit_logs(actor_id, performed_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource ON audit_logs(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_time ON audit_logs(performed_at DESC);

-- 2. HELPER FUNCTION TO RECORD AUDIT TRAIL SAFELY
CREATE OR REPLACE FUNCTION record_audit_log(
    p_actor_id UUID,
    p_action TEXT,
    p_resource_type TEXT,
    p_resource_id TEXT,
    p_old_values JSONB DEFAULT NULL,
    p_new_values JSONB DEFAULT NULL,
    p_ip TEXT DEFAULT NULL,
    p_user_agent TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    v_log_id UUID;
BEGIN
    INSERT INTO public.audit_logs (
        actor_id,
        action,
        resource_type,
        resource_id,
        old_values,
        new_values,
        ip_address,
        user_agent,
        performed_at
    )
    VALUES (
        COALESCE(p_actor_id, auth.uid()),
        p_action,
        p_resource_type,
        p_resource_id,
        p_old_values,
        p_new_values,
        p_ip,
        p_user_agent,
        now()
    )
    RETURNING id INTO v_log_id;

    RETURN v_log_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- >>> END OF 20260907000010_audit_logging.sql <<<


-- >>> START OF 20260907000011_transactional_functions.sql <<<
-- ============================================================================
-- Migration: 20260907000011_transactional_functions.sql
-- Description: Server-side ACID transactions (Pessimistic stock locking, slot booking, Haversine)
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. HAVERSINE GEOLOCATION DISTANCE (Pure SQL, no external PostGIS dependency required)
CREATE OR REPLACE FUNCTION calculate_distance_km(
    p_lat1 NUMERIC,
    p_lon1 NUMERIC,
    p_lat2 NUMERIC,
    p_lon2 NUMERIC
)
RETURNS NUMERIC AS $$
DECLARE
    v_r CONSTANT NUMERIC := 6371.0; -- Rayon terrestre moyen en kilomètres
    v_dlat NUMERIC;
    v_dlon NUMERIC;
    v_a NUMERIC;
    v_c NUMERIC;
BEGIN
    IF p_lat1 IS NULL OR p_lon1 IS NULL OR p_lat2 IS NULL OR p_lon2 IS NULL THEN
        RETURN NULL;
    END IF;

    v_dlat := radians(p_lat2 - p_lat1);
    v_dlon := radians(p_lon2 - p_lon1);

    v_a := sin(v_dlat / 2.0) * sin(v_dlat / 2.0) +
           cos(radians(p_lat1)) * cos(radians(p_lat2)) *
           sin(v_dlon / 2.0) * sin(v_dlon / 2.0);

    v_c := 2.0 * asin(sqrt(v_a));

    RETURN round((v_r * v_c)::numeric, 2);
END;
$$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

-- 2. TRANSACTIONAL STOCK DECREMENT WITH PESSIMISTIC ROW LOCKING (Anti Race-Condition)
-- Prevents two concurrent users from taking the last unit, forbidding negative stock
CREATE OR REPLACE FUNCTION reserve_and_decrement_stock(
    p_order_id UUID,
    p_items JSONB -- Array of {"product_id": "...", "quantity": 1}
)
RETURNS BOOLEAN AS $$
DECLARE
    v_item JSONB;
    v_prod_id UUID;
    v_req_qty INTEGER;
    v_cur_qty INTEGER;
    v_pharmacy_id UUID;
    v_prod_name TEXT;
BEGIN
    -- Verification: items array must not be empty
    IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
        RAISE EXCEPTION 'Le panier d''articles est vide.' USING ERRCODE = '22000';
    END IF;

    -- Iterate in sorted order of product_id to completely avoid SQL deadlocks
    FOR v_item IN 
        SELECT value FROM jsonb_array_elements(p_items) ORDER BY value->>'product_id'
    LOOP
        v_prod_id := (v_item->>'product_id')::UUID;
        v_req_qty := (v_item->>'quantity')::INTEGER;

        IF v_req_qty <= 0 THEN
            RAISE EXCEPTION 'Quantité invalide (%s) pour le produit %s', v_req_qty, v_prod_id
                USING ERRCODE = '22003';
        END IF;

        -- 1. PESSIMISTIC LOCK: Lock the stock row FOR UPDATE
        SELECT ps.current_quantity, ps.pharmacy_id, p.name
        INTO v_cur_qty, v_pharmacy_id, v_prod_name
        FROM public.product_stocks ps
        JOIN public.products p ON p.id = ps.product_id
        WHERE ps.product_id = v_prod_id
        FOR UPDATE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Produit introuvable ou stock non initialisé (ID: %s)', v_prod_id
                USING ERRCODE = 'P0002';
        END IF;

        -- 2. HARD GUARANTEE: Never allow current_quantity < requested_quantity
        IF v_cur_qty < v_req_qty THEN
            RAISE EXCEPTION 'Rupture de stock pour "%s" : demandé %s, disponible en officine %s.',
                v_prod_name, v_req_qty, v_cur_qty
                USING ERRCODE = 'P0001';
        END IF;

        -- 3. APPLY DECREMENT
        UPDATE public.product_stocks
        SET current_quantity = current_quantity - v_req_qty,
            updated_at = now()
        WHERE product_id = v_prod_id;

        -- 4. INSERT IMMUTABLE AUDIT MOVEMENT
        INSERT INTO public.stock_movements (
            product_id,
            pharmacy_id,
            movement_type,
            quantity_change,
            quantity_before,
            quantity_after,
            reference_type,
            reference_id,
            notes,
            performed_by
        )
        VALUES (
            v_prod_id,
            v_pharmacy_id,
            'sale',
            -v_req_qty,
            v_cur_qty,
            v_cur_qty - v_req_qty,
            'order',
            p_order_id::TEXT,
            'Décrémentation transactionnelle pour commande ' || p_order_id::TEXT,
            auth.uid()
        );
    END LOOP;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. TRANSACTIONAL CONCURRENCY-SAFE APPOINTMENT BOOKING
CREATE OR REPLACE FUNCTION book_appointment_slot(
    p_patient_id UUID,
    p_slot_id UUID,
    p_reason TEXT,
    p_mode consultation_mode_type DEFAULT 'in_person'
)
RETURNS UUID AS $$
DECLARE
    v_doctor_id UUID;
    v_start_time TIMESTAMPTZ;
    v_slot_status slot_status_type;
    v_appointment_id UUID;
BEGIN
    -- 1. PESSIMISTIC LOCK: Lock slot row FOR UPDATE
    SELECT doctor_id, start_time, status
    INTO v_doctor_id, v_start_time, v_slot_status
    FROM public.doctor_slots
    WHERE id = p_slot_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Le créneau demandé n''existe pas.' USING ERRCODE = 'P0002';
    END IF;

    -- 2. VERIFY AVAILABILITY
    IF v_slot_status != 'available' THEN
        RAISE EXCEPTION 'Ce créneau horaire a déjà été réservé par un autre patient.'
            USING ERRCODE = 'P0003';
    END IF;

    -- 3. MARK SLOT AS BOOKED
    UPDATE public.doctor_slots
    SET status = 'booked',
        updated_at = now()
    WHERE id = p_slot_id;

    -- 4. CREATE APPOINTMENT
    INSERT INTO public.appointments (
        patient_id,
        doctor_id,
        slot_id,
        scheduled_at,
        status,
        consultation_mode,
        reason_for_visit
    )
    VALUES (
        p_patient_id,
        v_doctor_id,
        p_slot_id,
        v_start_time,
        'confirmed',
        p_mode,
        p_reason
    )
    RETURNING id INTO v_appointment_id;

    -- 5. NOTIFY DOCTOR
    INSERT INTO public.notifications (
        recipient_id,
        title,
        message,
        notification_type,
        data
    )
    VALUES (
        v_doctor_id,
        'Nouveau rendez-vous réservé',
        'Un patient a réservé le créneau du ' || to_char(v_start_time, 'DD/MM/YYYY à HH24:MI'),
        'appointment',
        jsonb_build_object('appointment_id', v_appointment_id, 'slot_id', p_slot_id)
    );

    RETURN v_appointment_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. PATIENT-INITIATED PRESCRIPTION TRANSFER TO SPECIFIC PHARMACY
CREATE OR REPLACE FUNCTION transfer_prescription_to_pharmacy(
    p_prescription_id UUID,
    p_pharmacy_id UUID,
    p_notes TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    v_rx_patient_id UUID;
    v_rx_status prescription_status_type;
    v_transfer_id UUID;
BEGIN
    -- Verify prescription ownership
    SELECT patient_id, status
    INTO v_rx_patient_id, v_rx_status
    FROM public.prescriptions
    WHERE id = p_prescription_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Ordonnance introuvable.' USING ERRCODE = 'P0002';
    END IF;

    IF v_rx_patient_id != auth.uid() THEN
        RAISE EXCEPTION 'Action interdite : vous ne pouvez transférer que vos propres ordonnances.'
            USING ERRCODE = '42501';
    END IF;

    IF v_rx_status IN ('cancelled', 'expired') THEN
        RAISE EXCEPTION 'Impossible de transférer une ordonnance annulée ou expirée.'
            USING ERRCODE = 'P0004';
    END IF;

    -- Record transfer
    INSERT INTO public.prescription_pharmacy_transfers (
        prescription_id,
        patient_id,
        pharmacy_id,
        status,
        patient_notes,
        transferred_at
    )
    VALUES (
        p_prescription_id,
        auth.uid(),
        p_pharmacy_id,
        'pending',
        p_notes,
        now()
    )
    RETURNING id INTO v_transfer_id;

    RETURN v_transfer_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- >>> END OF 20260907000011_transactional_functions.sql <<<


-- >>> START OF 20260907000012_rls_security_policies.sql <<<
-- ============================================================================
-- Migration: 20260907000012_rls_security_policies.sql
-- Description: Complete Row Level Security (RLS) policies for medical & commercial privacy
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. SECURITY HELPER FUNCTIONS
CREATE OR REPLACE FUNCTION current_user_role()
RETURNS app_role AS $$
    SELECT role FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE sql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION is_pharmacy_staff_member(p_pharmacy_id UUID)
RETURNS BOOLEAN AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.pharmacy_staff
        WHERE pharmacy_id = p_pharmacy_id
          AND profile_id = auth.uid()
          AND is_active = true
    );
$$ LANGUAGE sql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION has_active_patient_access(p_patient_id UUID)
RETURNS BOOLEAN AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.doctor_patient_access
        WHERE doctor_id = auth.uid()
          AND patient_id = p_patient_id
          AND status = 'active'
          AND (expires_at IS NULL OR expires_at > now())
    );
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- 2. ENABLE ROW LEVEL SECURITY ON ALL 28 TABLES
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE doctor_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pharmacies ENABLE ROW LEVEL SECURITY;
ALTER TABLE pharmacy_staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE medical_dossiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE medical_record_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE doctor_patient_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE dossier_transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE doctor_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE prescriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE prescription_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE prescription_pharmacy_transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_stocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_fulfillments ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE insurance_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_insurances ENABLE ROW LEVEL SECURITY;
ALTER TABLE insurance_coverages ENABLE ROW LEVEL SECURITY;
ALTER TABLE insurance_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 3. PROFILES POLICIES
-- ============================================================================
CREATE POLICY "Profiles are viewable by authenticated users"
ON profiles FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can update own basic profile"
ON profiles FOR UPDATE TO authenticated
USING (id = auth.uid())
WITH CHECK (id = auth.uid());

-- ============================================================================
-- 4. PATIENT PROFILES POLICIES
-- ============================================================================
CREATE POLICY "Patients view own profile"
ON patient_profiles FOR SELECT TO authenticated
USING (
    profile_id = auth.uid() OR
    has_active_patient_access(profile_id) OR
    current_user_role() = 'platform_admin'
);

CREATE POLICY "Patients update own profile"
ON patient_profiles FOR UPDATE TO authenticated
USING (profile_id = auth.uid())
WITH CHECK (profile_id = auth.uid());

CREATE POLICY "Patients insert own profile"
ON patient_profiles FOR INSERT TO authenticated
WITH CHECK (profile_id = auth.uid());

-- ============================================================================
-- 5. DOCTOR PROFILES POLICIES
-- ============================================================================
CREATE POLICY "Doctor profiles viewable by all authenticated"
ON doctor_profiles FOR SELECT TO authenticated USING (true);

CREATE POLICY "Doctors manage own profile"
ON doctor_profiles FOR ALL TO authenticated
USING (profile_id = auth.uid() OR current_user_role() = 'platform_admin')
WITH CHECK (profile_id = auth.uid() OR current_user_role() = 'platform_admin');

-- ============================================================================
-- 6. PHARMACIES & STAFF POLICIES
-- ============================================================================
CREATE POLICY "Active pharmacies are public to view"
ON pharmacies FOR SELECT TO authenticated
USING (is_active = true OR is_pharmacy_staff_member(id) OR current_user_role() = 'platform_admin');

CREATE POLICY "Pharmacy staff can update own pharmacy"
ON pharmacies FOR UPDATE TO authenticated
USING (is_pharmacy_staff_member(id) OR current_user_role() = 'platform_admin');

CREATE POLICY "Staff list viewable by affiliated staff and admin"
ON pharmacy_staff FOR SELECT TO authenticated
USING (is_pharmacy_staff_member(pharmacy_id) OR profile_id = auth.uid() OR current_user_role() = 'platform_admin');

-- ============================================================================
-- 7. MEDICAL DOSSIERS & ENTRIES (STRICT HEALTH PRIVACY)
-- ============================================================================
CREATE POLICY "Patient views own medical dossier"
ON medical_dossiers FOR SELECT TO authenticated
USING (
    patient_id = auth.uid() OR
    has_active_patient_access(patient_id) OR
    current_user_role() = 'platform_admin'
);

CREATE POLICY "Patient or authorized doctor updates dossier"
ON medical_dossiers FOR UPDATE TO authenticated
USING (
    patient_id = auth.uid() OR
    has_active_patient_access(patient_id) OR
    current_user_role() = 'platform_admin'
);

CREATE POLICY "View medical record entries"
ON medical_record_entries FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM medical_dossiers md
        WHERE md.id = medical_record_entries.dossier_id
          AND (md.patient_id = auth.uid() OR has_active_patient_access(md.patient_id))
    ) OR current_user_role() = 'platform_admin'
);

CREATE POLICY "Authorized doctor inserts medical record entries"
ON medical_record_entries FOR INSERT TO authenticated
WITH CHECK (
    doctor_id = auth.uid() AND
    EXISTS (
        SELECT 1 FROM medical_dossiers md
        WHERE md.id = medical_record_entries.dossier_id
          AND has_active_patient_access(md.patient_id)
    )
);

-- Access delegation table policies
CREATE POLICY "View doctor patient access"
ON doctor_patient_access FOR SELECT TO authenticated
USING (doctor_id = auth.uid() OR patient_id = auth.uid() OR current_user_role() = 'platform_admin');

CREATE POLICY "Patient manages doctor access"
ON doctor_patient_access FOR ALL TO authenticated
USING (patient_id = auth.uid() OR current_user_role() = 'platform_admin');

-- Dossier transfers policies
CREATE POLICY "View dossier transfers"
ON dossier_transfers FOR SELECT TO authenticated
USING (from_doctor_id = auth.uid() OR to_doctor_id = auth.uid() OR patient_id = auth.uid());

CREATE POLICY "Doctors manage dossier transfers"
ON dossier_transfers FOR ALL TO authenticated
USING (from_doctor_id = auth.uid() OR to_doctor_id = auth.uid());

-- ============================================================================
-- 8. SLOTS, APPOINTMENTS & CONSULTATIONS
-- ============================================================================
CREATE POLICY "Slots are viewable by all authenticated users"
ON doctor_slots FOR SELECT TO authenticated USING (true);

CREATE POLICY "Doctors manage own slots"
ON doctor_slots FOR ALL TO authenticated
USING (doctor_id = auth.uid() OR current_user_role() = 'platform_admin');

CREATE POLICY "View appointments"
ON appointments FOR SELECT TO authenticated
USING (patient_id = auth.uid() OR doctor_id = auth.uid() OR current_user_role() = 'platform_admin');

CREATE POLICY "Patients create appointments"
ON appointments FOR INSERT TO authenticated
WITH CHECK (patient_id = auth.uid());

CREATE POLICY "Participants update appointments"
ON appointments FOR UPDATE TO authenticated
USING (patient_id = auth.uid() OR doctor_id = auth.uid() OR current_user_role() = 'platform_admin');

CREATE POLICY "View consultations"
ON consultations FOR SELECT TO authenticated
USING (patient_id = auth.uid() OR doctor_id = auth.uid() OR current_user_role() = 'platform_admin');

CREATE POLICY "Doctors manage consultations"
ON consultations FOR ALL TO authenticated
USING (doctor_id = auth.uid() OR current_user_role() = 'platform_admin');

-- ============================================================================
-- 9. PRESCRIPTIONS & TRANSFERS
-- ============================================================================
CREATE POLICY "View prescriptions"
ON prescriptions FOR SELECT TO authenticated
USING (
    patient_id = auth.uid() OR
    doctor_id = auth.uid() OR
    EXISTS (
        SELECT 1 FROM prescription_pharmacy_transfers ppt
        WHERE ppt.prescription_id = prescriptions.id
          AND is_pharmacy_staff_member(ppt.pharmacy_id)
    ) OR
    current_user_role() = 'platform_admin'
);

CREATE POLICY "Doctors create prescriptions"
ON prescriptions FOR INSERT TO authenticated
WITH CHECK (doctor_id = auth.uid());

CREATE POLICY "Doctors update prescriptions"
ON prescriptions FOR UPDATE TO authenticated
USING (doctor_id = auth.uid() OR current_user_role() = 'platform_admin');

CREATE POLICY "View prescription items"
ON prescription_items FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM prescriptions p
        WHERE p.id = prescription_items.prescription_id
          AND (
            p.patient_id = auth.uid() OR
            p.doctor_id = auth.uid() OR
            EXISTS (
                SELECT 1 FROM prescription_pharmacy_transfers ppt
                WHERE ppt.prescription_id = p.id
                  AND is_pharmacy_staff_member(ppt.pharmacy_id)
            )
          )
    ) OR current_user_role() = 'platform_admin'
);

CREATE POLICY "Doctors manage prescription items"
ON prescription_items FOR ALL TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM prescriptions p
        WHERE p.id = prescription_items.prescription_id
          AND p.doctor_id = auth.uid()
    )
);

CREATE POLICY "View prescription transfers"
ON prescription_pharmacy_transfers FOR SELECT TO authenticated
USING (
    patient_id = auth.uid() OR
    is_pharmacy_staff_member(pharmacy_id) OR
    current_user_role() = 'platform_admin'
);

CREATE POLICY "Patients create prescription transfers"
ON prescription_pharmacy_transfers FOR INSERT TO authenticated
WITH CHECK (patient_id = auth.uid());

CREATE POLICY "Pharmacies update prescription transfers"
ON prescription_pharmacy_transfers FOR UPDATE TO authenticated
USING (is_pharmacy_staff_member(pharmacy_id) OR current_user_role() = 'platform_admin');

-- ============================================================================
-- 10. PRODUCTS, STOCKS & MOVEMENTS (MARKETPLACE PRIVACY)
-- ============================================================================
CREATE POLICY "Active products are visible to marketplace"
ON products FOR SELECT TO authenticated
USING (is_active = true OR is_pharmacy_staff_member(pharmacy_id) OR current_user_role() = 'platform_admin');

CREATE POLICY "Pharmacies manage own products"
ON products FOR ALL TO authenticated
USING (is_pharmacy_staff_member(pharmacy_id) OR current_user_role() = 'platform_admin')
WITH CHECK (is_pharmacy_staff_member(pharmacy_id) OR current_user_role() = 'platform_admin');

-- Product categories are public in read
CREATE POLICY "Product categories are public"
ON product_categories FOR SELECT TO authenticated USING (true);

-- Product stocks: Public can see quantity for marketplace, pharmacy can manage
CREATE POLICY "Stocks viewable for availability check"
ON product_stocks FOR SELECT TO authenticated USING (true);

CREATE POLICY "Pharmacies manage own stocks"
ON product_stocks FOR ALL TO authenticated
USING (is_pharmacy_staff_member(pharmacy_id) OR current_user_role() = 'platform_admin');

-- Stock movements: Strictly private to each pharmacy
CREATE POLICY "Stock movements strictly private to pharmacy"
ON stock_movements FOR SELECT TO authenticated
USING (is_pharmacy_staff_member(pharmacy_id) OR current_user_role() = 'platform_admin');

-- ============================================================================
-- 11. CARTS & ORDERS
-- ============================================================================
CREATE POLICY "Patients manage own cart"
ON carts FOR ALL TO authenticated
USING (patient_id = auth.uid())
WITH CHECK (patient_id = auth.uid());

CREATE POLICY "Patients manage own cart items"
ON cart_items FOR ALL TO authenticated
USING (
    EXISTS (SELECT 1 FROM carts WHERE carts.id = cart_items.cart_id AND carts.patient_id = auth.uid())
);

CREATE POLICY "View orders"
ON orders FOR SELECT TO authenticated
USING (patient_id = auth.uid() OR current_user_role() = 'platform_admin');

CREATE POLICY "Patients create orders"
ON orders FOR INSERT TO authenticated
WITH CHECK (patient_id = auth.uid());

-- Order fulfillments: Partitioned by pharmacy
CREATE POLICY "View order fulfillments"
ON order_fulfillments FOR SELECT TO authenticated
USING (
    is_pharmacy_staff_member(pharmacy_id) OR
    EXISTS (SELECT 1 FROM orders WHERE orders.id = order_fulfillments.order_id AND orders.patient_id = auth.uid()) OR
    current_user_role() = 'platform_admin'
);

CREATE POLICY "Pharmacies update own fulfillments"
ON order_fulfillments FOR UPDATE TO authenticated
USING (is_pharmacy_staff_member(pharmacy_id) OR current_user_role() = 'platform_admin');

CREATE POLICY "View order items"
ON order_items FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM order_fulfillments ofl
        WHERE ofl.id = order_items.order_fulfillment_id
          AND (
            is_pharmacy_staff_member(ofl.pharmacy_id) OR
            EXISTS (SELECT 1 FROM orders o WHERE o.id = ofl.order_id AND o.patient_id = auth.uid())
          )
    ) OR current_user_role() = 'platform_admin'
);

-- ============================================================================
-- 12. INSURANCE, PAYMENTS & NOTIFICATIONS
-- ============================================================================
CREATE POLICY "Insurance providers are public"
ON insurance_providers FOR SELECT TO authenticated USING (true);

CREATE POLICY "Patients manage own insurances"
ON patient_insurances FOR ALL TO authenticated
USING (patient_id = auth.uid() OR current_user_role() = 'platform_admin');

CREATE POLICY "Insurance coverages are public"
ON insurance_coverages FOR SELECT TO authenticated USING (true);

CREATE POLICY "View insurance claims"
ON insurance_claims FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM patient_insurances pi
        WHERE pi.id = insurance_claims.patient_insurance_id
          AND pi.patient_id = auth.uid()
    ) OR current_user_role() = 'platform_admin'
);

CREATE POLICY "View payments"
ON payments FOR SELECT TO authenticated
USING (patient_id = auth.uid() OR current_user_role() = 'platform_admin');

CREATE POLICY "Users view and manage own notifications"
ON notifications FOR ALL TO authenticated
USING (recipient_id = auth.uid())
WITH CHECK (recipient_id = auth.uid());

CREATE POLICY "Audit logs viewable only by platform admin"
ON audit_logs FOR SELECT TO authenticated
USING (current_user_role() = 'platform_admin');

-- >>> END OF 20260907000012_rls_security_policies.sql <<<


-- >>> START OF 20260907000013_storage_and_realtime.sql <<<
-- ============================================================================
-- Migration: 20260907000013_storage_and_realtime.sql
-- Description: Supabase Storage buckets, bucket RLS & Realtime publication setup
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. SUPABASE STORAGE BUCKETS
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES 
    (
        'product-images',
        'product-images',
        true,
        5242880, -- 5 MB
        ARRAY['image/jpeg', 'image/png', 'image/webp']
    ),
    (
        'medical-documents',
        'medical-documents',
        false,
        20971520, -- 20 MB
        ARRAY['application/pdf', 'image/jpeg', 'image/png']
    ),
    (
        'prescriptions',
        'prescriptions',
        false,
        10485760, -- 10 MB
        ARRAY['application/pdf', 'image/jpeg', 'image/png']
    ),
    (
        'doctor-assets',
        'doctor-assets',
        false,
        5242880, -- 5 MB
        ARRAY['image/png', 'image/jpeg']
    )
ON CONFLICT (id) DO NOTHING;

-- Storage RLS: product-images (Public read, authenticated pharmacy upload)
CREATE POLICY "Public read product images"
ON storage.objects FOR SELECT
USING (bucket_id = 'product-images');

CREATE POLICY "Pharmacy staff upload product images"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'product-images');

CREATE POLICY "Pharmacy staff update/delete product images"
ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'product-images');

-- Storage RLS: medical-documents (Private to patient & authorized doctor)
CREATE POLICY "Private access to medical documents"
ON storage.objects FOR SELECT TO authenticated
USING (
    bucket_id = 'medical-documents' AND
    (
        (storage.foldername(name))[1] = auth.uid()::text OR
        has_active_patient_access(((storage.foldername(name))[1])::uuid) OR
        current_user_role() = 'platform_admin'
    )
);

CREATE POLICY "Upload medical documents"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
    bucket_id = 'medical-documents' AND
    (
        (storage.foldername(name))[1] = auth.uid()::text OR
        has_active_patient_access(((storage.foldername(name))[1])::uuid) OR
        current_user_role() = 'platform_admin'
    )
);

-- Storage RLS: prescriptions (Doctor and patient access)
CREATE POLICY "Access prescription documents"
ON storage.objects FOR SELECT TO authenticated
USING (
    bucket_id = 'prescriptions' AND
    (
        (storage.foldername(name))[1] = auth.uid()::text OR
        current_user_role() IN ('doctor', 'platform_admin')
    )
);

CREATE POLICY "Doctors upload prescription documents"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
    bucket_id = 'prescriptions' AND
    (
        current_user_role() = 'doctor' OR
        current_user_role() = 'platform_admin'
    )
);

-- Storage RLS: doctor-assets (Doctor only)
CREATE POLICY "Doctors access own assets"
ON storage.objects FOR ALL TO authenticated
USING (
    bucket_id = 'doctor-assets' AND
    (storage.foldername(name))[1] = auth.uid()::text
);

-- 2. SUPABASE REALTIME REPLICATION PUBLICATION
-- Enable realtime updates on key reactive tables
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
        ALTER PUBLICATION supabase_realtime ADD TABLE doctor_slots;
        ALTER PUBLICATION supabase_realtime ADD TABLE appointments;
        ALTER PUBLICATION supabase_realtime ADD TABLE order_fulfillments;
        ALTER PUBLICATION supabase_realtime ADD TABLE prescription_pharmacy_transfers;
        ALTER PUBLICATION supabase_realtime ADD TABLE product_stocks;
    END IF;
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- >>> END OF 20260907000013_storage_and_realtime.sql <<<


-- >>> START OF 20260907000014_seed_data.sql <<<
-- ============================================================================
-- Migration: 20260907000014_seed_data.sql
-- Description: Standard reference data (Categories, insurance providers, initial taxonomy)
-- Project: CareLink Healthcare Platform
-- ============================================================================

-- 1. REFERENCE PRODUCT CATEGORIES
INSERT INTO public.product_categories (id, name, slug, description)
VALUES
    ('c1111111-1111-1111-1111-111111111111', 'Antalgiques & Antipyrétiques', 'antalgiques-antipyretiques', 'Traitements de la douleur et de la fièvre (Paracétamol, Ibuprofène, etc.)'),
    ('c2222222-2222-2222-2222-222222222222', 'Antibiotiques & Antibactériens', 'antibiotiques', 'Médicaments antibactériens sous ordonnance'),
    ('c3333333-3333-3333-3333-333333333333', 'Anti-inflammatoires', 'anti-inflammatoires', 'Anti-inflammatoires stéroïdiens et non stéroïdiens'),
    ('c4444444-4444-4444-4444-444444444444', 'Cardiologie & Hypertension', 'cardiologie-hypertension', 'Traitements de l''hypertension artérielle et pathologies cardiaques'),
    ('c5555555-5555-5555-5555-555555555555', 'Gastro-entérologie', 'gastro-enterologie', 'Pansements gastriques, antidiarrhéiques, antispasmodiques'),
    ('c6666666-6666-6666-6666-666666666666', 'Vitamines & Compléments', 'vitamines-complements', 'Minéraux, compléments alimentaires, oligo-éléments'),
    ('c7777777-7777-7777-7777-777777777777', 'Premiers secours & Soins', 'premiers-secours', 'Pansements, désinfectants, compresses stériles'),
    ('c8888888-8888-8888-8888-888888888888', 'Mère & Enfant', 'mere-enfant', 'Pédiatrie, laits infantiles, soins pour bébés et mamans')
ON CONFLICT (slug) DO NOTHING;

-- 2. REFERENCE INSURANCE PROVIDERS (Tiers-Payant Afrique de l'Ouest)
INSERT INTO public.insurance_providers (id, name, code, contact_phone, contact_email)
VALUES
    ('i1111111-1111-1111-1111-111111111111', 'SUNU Assurances', 'SUNU', '+228 22 21 10 33', 'contact.togo@sunu-group.com'),
    ('i2222222-2222-2222-2222-222222222222', 'NSIA Assurances', 'NSIA', '+228 22 23 20 00', 'contact@groupensia.com'),
    ('i3333333-3333-3333-3333-333333333333', 'ASCOMA Courtage', 'ASCOMA', '+228 22 21 34 50', 'info.togo@ascoma.com'),
    ('i4444444-4444-4444-4444-444444444444', 'SANLAM Assurance', 'SANLAM', '+228 22 53 45 00', 'contact@sanlam.tg'),
    ('i5555555-5555-5555-5555-555555555555', 'OGAR Assurances', 'OGAR', '+228 22 21 68 00', 'contact@ogar.tg')
ON CONFLICT (code) DO NOTHING;

-- >>> END OF 20260907000014_seed_data.sql <<<

