<template>
  <div class="hm"><header><div><h1>🩺 Espace Médecin CareLink</h1><p>Rendez-vous · Consultation · Ordonnance</p></div><button v-if="session" @click="signOut">Déconnexion</button></header>
  <main>
    <section v-if="!session" class="card"><h2>Connexion médecin</h2><p v-if="error" class="error">{{ error }}</p><form @submit.prevent="signIn"><input v-model="email" type="email" placeholder="Email" required><input v-model="password" type="password" placeholder="Mot de passe" required><button :disabled="loading">{{loading?'Connexion…':'Se connecter'}}</button></form></section>
    <template v-else>
      <section class="card"><h2>{{displayName}}</h2><p>Rôle : {{profile?.role||'—'}} · Spécialité : {{doctorProfile?.specialty||'—'}}</p><p v-if="error" class="error">{{error}}</p><p v-if="success" class="success">{{success}}</p></section>
      <section class="card"><h2>📅 Mes rendez-vous</h2><button @click="loadData">Actualiser</button><div v-if="!appointments.length">Aucun rendez-vous.</div><article v-for="a in appointments" :key="a.id" class="item"><strong>{{a.patient_name}}</strong><p>{{formatDate(a.scheduled_at)}} · {{a.status}}</p><p>{{a.reason_for_visit||'Consultation'}}</p><button v-if="a.status==='confirmed'||a.status==='requested'" @click="start(a)">Prendre le patient</button><button v-else-if="a.status==='in_progress'" @click="start(a)">Continuer</button></article></section>
      <section v-if="current" class="card"><h2>🩺 Consultation de {{current.patient_name}}</h2><label>Température</label><input v-model="rx.temperature" placeholder="37.2"><label>Pouls (BPM)</label><input v-model="rx.bpm" placeholder="78"><label>Tension</label><input v-model="rx.bloodPressure" placeholder="120/80"><label>Diagnostic</label><input v-model="rx.diagnosis" placeholder="Diagnostic"><label>Notes cliniques</label><textarea v-model="rx.notes" rows="3"></textarea><label>Médicaments (une ligne par médicament)</label><textarea v-model="rx.prescription" rows="5" placeholder="Paracétamol 500 mg\nAmoxicilline 500 mg"></textarea><label>Instructions</label><textarea v-model="rx.instructions" rows="3"></textarea><button :disabled="busy" @click="savePrescription">💾 Terminer et émettre l’ordonnance</button></section>
      <section class="card"><h2>📆 Publier un créneau</h2><input v-model="slotStart" type="datetime-local"><input v-model="slotEnd" type="datetime-local"><button @click="createSlot">Publier</button></section>
    </template>
  </main></div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import type { Session } from '@supabase/supabase-js';
import { supabase } from './lib/supabase';
const session=ref<Session|null>(null),profile=ref<any>(null),doctorProfile=ref<any>(null),appointments=ref<any[]>([]),current=ref<any>(null),loading=ref(false),busy=ref(false),error=ref(''),success=ref(''),email=ref(''),password=ref(''),slotStart=ref(''),slotEnd=ref('');
const consultationId=ref<string|null>(null);
const rx=reactive({temperature:'',bpm:'',bloodPressure:'',diagnosis:'',notes:'',prescription:'',instructions:''});
const displayName=computed(()=>profile.value?`Dr. ${profile.value.first_name||''} ${profile.value.last_name||''}`.trim():'Médecin');
function formatDate(d:string){return new Date(d).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'});}
async function loadData(){if(!session.value?.user)return;loading.value=true;error.value='';try{const {data:p,error:e}=await supabase.from('profiles').select('*,doctor_profiles(*)').eq('id',session.value.user.id).single();if(e)throw e;profile.value=p;doctorProfile.value=Array.isArray(p.doctor_profiles)?p.doctor_profiles[0]:p.doctor_profiles;const {data,error:ae}=await supabase.from('appointments').select('id,scheduled_at,status,reason_for_visit,consultation_mode,patient:profiles!appointments_patient_id_fkey(first_name,last_name)').eq('doctor_id',session.value.user.id).order('scheduled_at',{ascending:true}).limit(50);if(ae)throw ae;appointments.value=(data||[]).map((a:any)=>({...a,patient_name:`${a.patient?.first_name||''} ${a.patient?.last_name||''}`.trim()||'Patient'}));}catch(e:any){error.value=e.message||'Chargement impossible.';}finally{loading.value=false;}}
async function start(a:any){busy.value=true;error.value='';try{const {data,error:e}=await supabase.rpc('start_consultation',{p_appointment_id:a.id});if(e)throw e;consultationId.value=data;current.value=a;rx.temperature='';rx.bpm='';rx.bloodPressure='';rx.diagnosis='';rx.notes='';rx.prescription='';rx.instructions='';success.value='Consultation ouverte.';}catch(e:any){error.value=e.message||'Impossible de démarrer la consultation.';}finally{busy.value=false;}}
async function savePrescription(){if(!consultationId.value||!session.value?.user)return;const lines=rx.prescription.split('\n').map(s=>s.trim()).filter(Boolean);if(!rx.diagnosis.trim()||!lines.length){error.value='Diagnostic et au moins un médicament sont obligatoires.';return;}busy.value=true;error.value='';try{const vitalSigns={temperature:rx.temperature||null,pulse_bpm:rx.bpm||null,blood_pressure:rx.bloodPressure||null};const {data,error:e}=await supabase.rpc('complete_consultation_and_issue_prescription',{p_consultation_id:consultationId.value,p_diagnosis:rx.diagnosis.trim(),p_clinical_notes:`${rx.notes}\nConstantes: ${JSON.stringify(vitalSigns)}`,p_treatment_plan:rx.instructions||null,p_prescription_items:lines.map(m=>({medication_name:m,product_name:m,quantity:1,duration_days:7,dosage:'selon ordonnance',frequency:'selon prescription',instructions:rx.instructions||null})),p_prescription_instructions:rx.instructions||null});if(e)throw e;success.value=`Ordonnance ${data?.prescription_code||''} émise pour ${current.value.patient_name}.`;current.value=null;consultationId.value=null;await loadData();}catch(e:any){error.value=e.message||'Impossible d’émettre l’ordonnance.';}finally{busy.value=false;}}
async function createSlot(){if(!session.value?.user||!slotStart.value||!slotEnd.value)return;const start=new Date(slotStart.value),end=new Date(slotEnd.value);if(end<=start){error.value='La fin doit être après le début.';return;}const {error:e}=await supabase.from('doctor_slots').insert({doctor_id:session.value.user.id,start_time:start.toISOString(),end_time:end.toISOString(),status:'available',consultation_mode:'in_person',capacity:1});if(e)error.value=e.message;else{success.value='Créneau publié.';slotStart.value='';slotEnd.value='';}}
async function signIn(){loading.value=true;error.value='';try{const {data,error:e}=await supabase.auth.signInWithPassword({email:email.value,password:password.value});if(e)throw e;session.value=data.session;await loadData();}catch(e:any){error.value=e.message||'Connexion impossible.';}finally{loading.value=false;}}
async function signOut(){await supabase.auth.signOut();session.value=null;profile.value=null;doctorProfile.value=null;appointments.value=[];current.value=null;}
onMounted(async()=>{const {data}=await supabase.auth.getSession();session.value=data.session;if(session.value)await loadData();supabase.auth.onAuthStateChange((_e,s)=>{session.value=s;});});
</script>

<style scoped>
:global(body){margin:0;font-family:Arial,sans-serif;background:#f4f7fb;color:#222}.hm header{background:#198754;color:#fff;padding:16px 20px;display:flex;justify-content:space-between;align-items:center}.hm main{max-width:760px;margin:auto;padding:16px;display:grid;gap:14px}.card{background:#fff;border-radius:14px;padding:18px;box-shadow:0 2px 10px rgba(0,0,0,.08)}input,textarea{display:block;width:100%;box-sizing:border-box;padding:11px;margin:7px 0;border:1px solid #ccc;border-radius:8px}button{padding:10px 14px;border:0;border-radius:8px;margin:4px;cursor:pointer}.item{border:1px solid #ddd;border-radius:10px;padding:12px;margin-top:10px}.error{color:#b42318}.success{color:#067647}label{font-weight:600;display:block;margin-top:10px}
</style>
