"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, FileSignature, Pill, Save, ShieldCheck, UserRound } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { useParams, useRouter } from "next/navigation";

export default function PrescriptionPage(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const supabase=createClient();
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const [doctorId,setDoctorId]=useState(""); const [patientId,setPatientId]=useState(""); const [patientName,setPatientName]=useState("Patient"); const [doctorName,setDoctorName]=useState("Médecin");
 const [medications,setMedications]=useState(""); const [instructions,setInstructions]=useState(""); const [temperature,setTemperature]=useState(""); const [bpm,setBpm]=useState(""); const [bloodPressure,setBloodPressure]=useState("");
 useEffect(()=>{load()},[]);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/hospital/login");return;}const {data:d}=await supabase.from("doctors").select("id,display_name").eq("profile_id",user.id).maybeSingle();if(!d){router.replace("/hospital/unauthorized");return;}setDoctorId(d.id);setDoctorName(d.display_name||"Médecin");const {data:a}=await supabase.from("appointments").select("patient_id").eq("id",id).eq("assigned_doctor_id",d.id).maybeSingle();if(!a){router.replace("/hospital/doctor");return;}setPatientId(a.patient_id);const {data:p}=await supabase.from("profiles").select("full_name").eq("id",a.patient_id).maybeSingle();setPatientName(p?.full_name||`Patient ${a.patient_id.slice(0,8)}`);const {data:r}=await supabase.from("prescriptions").select("medications,instructions,temperature,bpm,blood_pressure,doctor_name").eq("appointment_id",id).maybeSingle();if(r){setMedications(r.medications||"");setInstructions(r.instructions||"");setTemperature(r.temperature||"");setBpm(r.bpm||"");setBloodPressure(r.blood_pressure||"")}setLoading(false)}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");const {error}=await supabase.from("prescriptions").upsert({appointment_id:id,doctor_id:doctorId,patient_id:patientId,temperature,bpm,blood_pressure: bloodPressure,medications,instructions,doctor_name:doctorName,status:"sent",sent_at:new Date().toISOString()},{onConflict:"appointment_id"});if(error)setMessage(error.message);else setMessage("Ordonnance enregistrée et envoyée dans l’espace patient.");setSaving(false)}
 if(loading)return <main className="min-h-screen flex items-center justify-center bg-slate-50"><div className="h-9 w-9 animate-spin rounded-full border-4 border-slate-200 border-t-slate-950"/></main>;
 return <main className="min-h-screen bg-[#f5f7fb] text-slate-900"><header className="border-b border-slate-200 bg-white px-5 py-4"><div className="mx-auto flex max-w-5xl items-center gap-3"><Link href={`/hospital/doctor/consultation/${id}`} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div><p className="text-xs text-slate-400">CareLink Hôpital / Prescription</p><h1 className="font-bold">Ordonnance électronique</h1></div></div></header><form onSubmit={save} className="mx-auto max-w-5xl space-y-5 p-5 sm:p-8"><section className="rounded-2xl bg-slate-950 p-6 text-white"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/10"><UserRound size={25}/></div><div><p className="text-xs uppercase tracking-wider text-slate-400">Patient</p><h2 className="text-2xl font-bold">{patientName}</h2><p className="text-sm text-slate-400">Prescripteur : {doctorName}</p></div></div></section><section className="grid gap-5 md:grid-cols-2"><Card icon={<Pill size={18}/>} title="Médicaments"><textarea className="field" rows={10} value={medications} onChange={e=>setMedications(e.target.value)} placeholder="Nom du médicament, dosage, forme, quantité…"/></Card><Card icon={<FileSignature size={18}/>} title="Posologie et instructions"><textarea className="field" rows={10} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Posologie, fréquence, durée et recommandations…"/></Card></section><Card icon={<ShieldCheck size={18}/>} title="Constantes"><div className="grid gap-3 sm:grid-cols-3"><Field label="Température" value={temperature} set={setTemperature} placeholder="°C"/><Field label="Fréquence cardiaque" value={bpm} set={setBpm} placeholder="bpm"/><Field label="Pression artérielle" value={bloodPressure} set={setBloodPressure} placeholder="mmHg"/></div></Card><div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-lg sm:flex-row sm:items-center sm:justify-between"><p className="text-sm">{message&&<span className={message.includes("envoyée")?"font-semibold text-emerald-700":"text-rose-700"}>{message}</span>}</p><button disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-6 py-3 text-sm font-bold text-white disabled:opacity-50"><Save size={17}/>{saving?"Enregistrement…":"Signer et envoyer au patient"}</button></div></form></main>;
}
function Card({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2 font-bold"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100">{icon}</span>{title}</div>{children}</section>}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <label className="text-xs font-semibold text-slate-500">{label}<input className="field mt-1" value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></label>}
