<template>
  <AppLayout page-title="Détail commande">
    <div v-if="loading" class="dash-loading"><div class="spinner"/></div>
    <div v-else-if="!order" class="dash-section dash-empty"><p class="dash-empty-title">Commande introuvable</p><RouterLink to="/orders" class="btn btn-primary btn-sm">Retour</RouterLink></div>
    <template v-else>
      <section class="dash-section"><div class="dash-section-header"><h2>{{order.order_number}}</h2><span class="badge">{{order.status}}</span></div><p class="dash-list-meta">{{formatDate(order.created_at)}}</p><div style="margin-top:12px;display:grid;gap:6px;font-size:13px"><div style="display:flex;justify-content:space-between"><span>Total</span><strong>{{formatPrice(Number(order.total_amount))}}</strong></div><div style="display:flex;justify-content:space-between"><span>Assurance</span><span>{{formatPrice(Number(order.insurance_amount||0))}}</span></div><div style="display:flex;justify-content:space-between"><span>À charge</span><strong>{{formatPrice(Number(order.patient_amount||order.total_amount))}}</strong></div><div style="display:flex;justify-content:space-between"><span>Paiement</span><span>{{order.payment_status}}</span></div></div><p v-if="error" class="alert alert-error" style="margin-top:12px">{{error}}</p><p v-if="success" class="alert alert-success" style="margin-top:12px">{{success}}</p><div v-if="order.payment_status!=='succeeded'" style="margin-top:12px"><label class="form-label">Mode de paiement</label><select v-model="paymentMethod" class="input"><option value="tmoney">TMoney</option><option value="yas">Yas</option><option value="moov_money">Moov Money</option><option value="card">Carte</option><option value="cash_on_delivery">Paiement à la livraison</option><option value="cash_in_person">Paiement sur place</option></select><button class="btn btn-primary" style="width:100%;margin-top:8px" :disabled="paying" @click="pay">{{paying?'Paiement…':'Payer maintenant (simulation)'}}</button></div></section>
      <section v-for="f in fulfillments" :key="f.id" class="dash-section"><div class="dash-section-header"><h2>{{f.pharmacy_name}}</h2><span class="badge">{{f.status}}</span></div><p class="dash-list-meta">{{f.fulfillment_number}} · {{formatPrice(Number(f.subtotal_amount))}}</p><div class="dash-list" style="margin-top:10px"><div v-for="it in f.items" :key="it.id" class="dash-list-item"><div class="dash-list-body"><div class="dash-list-title">{{it.product_name}}</div><div class="dash-list-meta">x{{it.quantity}} · {{formatPrice(Number(it.unit_price))}}</div></div><strong>{{formatPrice(Number(it.total_price||it.line_total))}}</strong></div></div></section>
      <RouterLink to="/orders" class="btn btn-secondary" style="width:100%">Retour aux commandes</RouterLink>
    </template>
  </AppLayout>
</template>
<script setup lang="ts">
import {ref,onMounted} from 'vue';import {RouterLink,useRoute} from 'vue-router';import AppLayout from '@/components/layout/AppLayout.vue';import {useAuthStore} from '@/stores/auth';import {supabase} from '@/lib/supabase';
const route=useRoute(),auth=useAuthStore(),loading=ref(true),order=ref<any>(null),fulfillments=ref<any[]>([]),paymentMethod=ref('tmoney'),paying=ref(false),error=ref(''),success=ref('');
function formatPrice(n:number){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'XOF',maximumFractionDigits:0}).format(n);}function formatDate(d:string){return new Date(d).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'});}
async function load(){if(!auth.user)return;const id=String(route.params.id);const {data:o,error:e}=await supabase.from('orders').select('*').eq('id',id).eq('patient_id',auth.user.id).maybeSingle();if(e){error.value=e.message;loading.value=false;return;}order.value=o;if(o){const {data:f,error:fe}=await supabase.from('order_fulfillments').select('id,fulfillment_number,status,subtotal_amount,created_at,pharmacies(name),order_items(id,product_name,quantity,unit_price,line_total,total_price)').eq('order_id',o.id);if(fe)error.value=fe.message;fulfillments.value=(f||[]).map((x:any)=>({...x,pharmacy_name:x.pharmacies?.name||'Pharmacie',items:x.order_items||[]}));}loading.value=false;}
async function pay(){if(!order.value)return;paying.value=true;error.value='';success.value='';try{const {data,error:e}=await supabase.rpc('simulate_order_payment',{p_order_id:order.value.id,p_payment_method:paymentMethod.value});if(e)throw e;success.value=`Paiement simulé confirmé : ${data?.amount?formatPrice(Number(data.amount)):''}`;await load();}catch(e:any){error.value=e.message||'Paiement impossible.';}finally{paying.value=false;}}
onMounted(load);
</script>
