"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Building2, CheckCircle2, Plus, Stethoscope, Users, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function ConfigurationPage(){
 const supabase=createClient();
 const [hospitalId,setHospitalId]=useState(""); const [hospitalName,setHospitalName]=useState("Hôpital"); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const [specialties,setSpecialties]=useState<any[]>([]); const [desks,setDesks]=useState<any[]>([]); const [doctors,setDoctors]=useState<any[]>([]);
 const [specName,setSpecName]=useState(""); const [specCode,setSpecCode]=useState(""); const [deskName,setDeskName]=useState(""); const [deskCode,setDeskCode]=useState(""); const [doctorName,setDoctorName]=useState(""); const [doctorProfile,setDoctorProfile]=useState(""); const [doctorSpec,setDoctorSpec]=useState("");
 useEffect(()=>{load()},[]);
 async function load(){setLoading(true);setError("");const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/hospital/login";return;}const {data:staff,error:se}=await supabase.from("hospital_staff").select("hospital_id,display_name,role").eq("profile_id",user.id).eq("role","hospital_admin").eq("is_active",true).maybeSingle();if(se||!staff){setError("Accès administrateur requis.");setLoading(false);return;}setHospitalId(staff.hospital_id);setHospitalName(staff.display_name||"Hôpital");await refresh(staff.hospital_id);setLoading(false)}
 async function refresh(hid:string){const [s,d,r]=await Promise.all([supabase.from("specialties").select("id,name,code,is_active").eq("hospital_id",hid).order("name"),supabase.from("doctors").select("id,display_name,specialty_id,is_available").eq("hospital_id",hid).order("display_name"),supabase.from("reception_desks").select("id,name,code,is_active").eq("hospital_id",hid).order("name")]);setSpecialties(s.data||[]);setDoctors(d.data||[]);setDesks(r.data||[]);if(s.error||d.error||r.error)setError((s.error||d.error||r.error)?.message||"")}
 async function addSpecialty(e:FormEvent){e.preventDefault();if(!specName||!specCode)return;const {error}=await supabase.from("specialties").insert({hospital_id:hospitalId,name:specName,code:specCode.toUpperCase(),is_active:true});if(error)setError(error.message);else{setSpecName("");setSpecCode("");await refresh(hospitalId)}}
 async function addDesk(e:FormEvent){e.preventDefault();if(!deskName||!deskCode)return;const {error}=await supabase.from("reception_desks").insert({hospital_id:hospitalId,name:deskName,code:deskCode.toUpperCase(),is_active:true});if(error)setError(error.message);else{setDeskName("");setDeskCode("");await refresh(hospitalId)}}
 async function addDoctor(e:FormEvent){e.preventDefault();if(!doctorName||!doctorProfile)return;const {error}=await supabase.from("doctors").insert({hospital_id:hospitalId,display_name:doctorName,profile_id:doctorProfile,specialty_id:doctorSpec||null,is_available:true});if(error)setError(error.message);else{setDoctorName("");setDoctorProfile("");setDoctorSpec("");await refresh(hospitalId)}}
 if(loading)return <main className="min-h-screen grid place-items-center bg-slate-50"><div className="h-9 w-9 animate-spin rounded-full border-4 border-slate-200 border-t-slate-950"/></main>;
 return <main className="min-h-screen bg-[#f5f7fb] text-slate-900"><header className="border-b border-slate-200 bg-white px-5 py-4"><div className="mx-auto flex max-w-6xl items-center gap-3"><Link href="/hospital/admin" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div><p className="text-xs text-slate-400">CareLink Hôpital / Administration</p><h1 className="font-bold">Configuration de l’établissement</h1></div></div></header><div className="mx-auto max-w-6xl space-y-6 p-5 sm:p-8"><section className="rounded-3xl bg-slate-950 p-7 text-white"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-white/10"><Building2/></div><div><p className="text-xs uppercase tracking-wider text-slate-400">Établissement</p><h2 className="text-2xl font-bold">{hospitalName}</h2><p className="text-sm text-slate-400">Paramétrez les ressources utilisées par l’accueil et les médecins.</p></div></div></section>{error&&<div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}<div className="grid gap-5 lg:grid-cols-3"><Panel icon={<Stethoscope/>} title="Spécialités" items={specialties} label={x=>`${x.name} · ${x.code}`} form={<form onSubmit={addSpecialty} className="space-y-2"><Input value={specName} set={setSpecName} placeholder="Ex. Médecine générale"/><Input value={specCode} set={setSpecCode} placeholder="Code"/><button className="btn"><Plus size={16}/>Ajouter</button></form>}/><Panel icon={<Building2/>} title="Postes d’accueil" items={desks} label={x=>`${x.name} · ${x.code}`} form={<form onSubmit={addDesk} className="space-y-2"><Input value={deskName} set={setDeskName} placeholder="Ex. Accueil principal"/><Input value={deskCode} set={setDeskCode} placeholder="Code"/><button className="btn"><Plus size={16}/>Ajouter</button></form>}/><Panel icon={<Users/>} title="Médecins" items={doctors} label={x=>`${x.display_name||"Médecin"}${specialties.find(s=>s.id===x.specialty_id)?` · ${specialties.find(s=>s.id===x.specialty_id).name}`:""}`} form={<form onSubmit={addDoctor} className="space-y-2"><Input value={doctorName} set={setDoctorName} placeholder="Nom affiché du médecin"/><Input value={doctorProfile} set={setDoctorProfile} placeholder="UUID du profil utilisateur"/><select className="field" value={doctorSpec} onChange={e=>setDoctorSpec(e.target.value)}><option value="">Spécialité</option>{specialties.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="btn"><Plus size={16}/>Ajouter</button></form>}/></div><p className="text-xs text-slate-400">Les médecins doivent disposer d’un profil utilisateur CareLink. L’UUID est utilisé uniquement pour rattacher le compte au dossier médecin.</p></div></main>
}
function Panel({icon,title,items,label,form}:{icon:React.ReactNode;title:string;items:any[];label:(x:any)=>string;form:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100">{icon}</span><div><h2 className="font-bold">{title}</h2><p className="text-xs text-slate-400">{items.length} configuré(s)</p></div></div><div className="mb-4 space-y-2">{items.length?items.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm"><span>{label(x)}</span><CheckCircle2 size={15} className="text-emerald-600"/></div>):<p className="rounded-xl border border-dashed border-slate-200 p-4 text-xs text-slate-400">Aucun élément configuré.</p>}</div>{form}</section>}
function Input({value,set,placeholder}:{value:string;set:(v:string)=>void;placeholder:string}){return <input className="field" value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} required/>}
